In [13]:
import torch
import numpy as np
import math
# import torch.nn.functional as F
import torch.nn as nn

In [15]:
vocab_size = 100
d_model = 300

nn.Embedding(100, 300)
# F.embedding(100, 300)

Embedding(100, 300)

In [16]:
nn.Embedding(100, 300) * math.sqrt(d_model)

TypeError: unsupported operand type(s) for *: 'Embedding' and 'float'

In [23]:
seq_len = 128

In [28]:
pe = torch.zeros(seq_len, d_model)
pe.shape

torch.Size([128, 300])

In [29]:
position = torch.arange(0, seq_len, dtype=torch.float).unsqueeze(1)
position

tensor([[  0.],
        [  1.],
        [  2.],
        [  3.],
        [  4.],
        [  5.],
        [  6.],
        [  7.],
        [  8.],
        [  9.],
        [ 10.],
        [ 11.],
        [ 12.],
        [ 13.],
        [ 14.],
        [ 15.],
        [ 16.],
        [ 17.],
        [ 18.],
        [ 19.],
        [ 20.],
        [ 21.],
        [ 22.],
        [ 23.],
        [ 24.],
        [ 25.],
        [ 26.],
        [ 27.],
        [ 28.],
        [ 29.],
        [ 30.],
        [ 31.],
        [ 32.],
        [ 33.],
        [ 34.],
        [ 35.],
        [ 36.],
        [ 37.],
        [ 38.],
        [ 39.],
        [ 40.],
        [ 41.],
        [ 42.],
        [ 43.],
        [ 44.],
        [ 45.],
        [ 46.],
        [ 47.],
        [ 48.],
        [ 49.],
        [ 50.],
        [ 51.],
        [ 52.],
        [ 53.],
        [ 54.],
        [ 55.],
        [ 56.],
        [ 57.],
        [ 58.],
        [ 59.],
        [ 60.],
        [ 61.],
        

In [30]:
div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-np.log(10000.0) / d_model))
div_term

tensor([1.0000e+00, 9.4044e-01, 8.8444e-01, 8.3176e-01, 7.8223e-01, 7.3564e-01,
        6.9183e-01, 6.5063e-01, 6.1188e-01, 5.7544e-01, 5.4117e-01, 5.0894e-01,
        4.7863e-01, 4.5013e-01, 4.2332e-01, 3.9811e-01, 3.7440e-01, 3.5210e-01,
        3.3113e-01, 3.1141e-01, 2.9286e-01, 2.7542e-01, 2.5902e-01, 2.4359e-01,
        2.2909e-01, 2.1544e-01, 2.0261e-01, 1.9055e-01, 1.7920e-01, 1.6853e-01,
        1.5849e-01, 1.4905e-01, 1.4017e-01, 1.3183e-01, 1.2397e-01, 1.1659e-01,
        1.0965e-01, 1.0312e-01, 9.6977e-02, 9.1201e-02, 8.5770e-02, 8.0662e-02,
        7.5858e-02, 7.1340e-02, 6.7091e-02, 6.3096e-02, 5.9338e-02, 5.5804e-02,
        5.2481e-02, 4.9355e-02, 4.6416e-02, 4.3652e-02, 4.1052e-02, 3.8607e-02,
        3.6308e-02, 3.4145e-02, 3.2112e-02, 3.0200e-02, 2.8401e-02, 2.6710e-02,
        2.5119e-02, 2.3623e-02, 2.2216e-02, 2.0893e-02, 1.9649e-02, 1.8478e-02,
        1.7378e-02, 1.6343e-02, 1.5370e-02, 1.4454e-02, 1.3594e-02, 1.2784e-02,
        1.2023e-02, 1.1307e-02, 1.0633e-

In [31]:
pe[:,0::2] = torch.sin(position * div_term)
pe

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 8.4147e-01,  0.0000e+00,  8.0782e-01,  ...,  0.0000e+00,
          1.0633e-04,  0.0000e+00],
        [ 9.0930e-01,  0.0000e+00,  9.5231e-01,  ...,  0.0000e+00,
          2.1267e-04,  0.0000e+00],
        ...,
        [-6.1604e-01,  0.0000e+00, -9.6788e-01,  ...,  0.0000e+00,
          1.3291e-02,  0.0000e+00],
        [ 3.2999e-01,  0.0000e+00, -7.7358e-01,  ...,  0.0000e+00,
          1.3398e-02,  0.0000e+00],
        [ 9.7263e-01,  0.0000e+00,  5.5943e-02,  ...,  0.0000e+00,
          1.3504e-02,  0.0000e+00]])

In [35]:
pe[:,1::2] = torch.cos(position * div_term)
pe

tensor([[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  ...,  1.0000e+00,
          0.0000e+00,  1.0000e+00],
        [ 8.4147e-01,  5.4030e-01,  8.0782e-01,  ...,  1.0000e+00,
          1.0633e-04,  1.0000e+00],
        [ 9.0930e-01, -4.1615e-01,  9.5231e-01,  ...,  1.0000e+00,
          2.1267e-04,  1.0000e+00],
        ...,
        [-6.1604e-01,  7.8771e-01, -9.6788e-01,  ...,  9.9990e-01,
          1.3291e-02,  9.9991e-01],
        [ 3.2999e-01,  9.4398e-01, -7.7358e-01,  ...,  9.9990e-01,
          1.3398e-02,  9.9991e-01],
        [ 9.7263e-01,  2.3236e-01,  5.5943e-02,  ...,  9.9990e-01,
          1.3504e-02,  9.9991e-01]])

In [36]:
pe.unsqueeze(0)

tensor([[[ 0.0000e+00,  1.0000e+00,  0.0000e+00,  ...,  1.0000e+00,
           0.0000e+00,  1.0000e+00],
         [ 8.4147e-01,  5.4030e-01,  8.0782e-01,  ...,  1.0000e+00,
           1.0633e-04,  1.0000e+00],
         [ 9.0930e-01, -4.1615e-01,  9.5231e-01,  ...,  1.0000e+00,
           2.1267e-04,  1.0000e+00],
         ...,
         [-6.1604e-01,  7.8771e-01, -9.6788e-01,  ...,  9.9990e-01,
           1.3291e-02,  9.9991e-01],
         [ 3.2999e-01,  9.4398e-01, -7.7358e-01,  ...,  9.9990e-01,
           1.3398e-02,  9.9991e-01],
         [ 9.7263e-01,  2.3236e-01,  5.5943e-02,  ...,  9.9990e-01,
           1.3504e-02,  9.9991e-01]]])

In [34]:
pe.unsqueeze(0).shape

torch.Size([1, 128, 300])

In [37]:
nn.Parameter(torch.ones(1))

Parameter containing:
tensor([1.], requires_grad=True)

In [38]:
nn.Parameter(torch.zeros(1))

Parameter containing:
tensor([0.], requires_grad=True)